INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Juan", "Valdez", "juanxsvaldez@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Camilo", "Gutierrez", "camiloGZ@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Mr. Jhon", "Doe", "jhon_doe@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Linus", "Torvalds", "linustorvals@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Rasmus", "Lerdford", "rasmuss.lerdford@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Erich", "gamma", "Erich_gamma_@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Richard", "Helm", "Richard_Helm@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Salomon", "King", "salomonKing@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("David", "king", "davidKing@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Charles", "Chaplin", "CharlesChaplin1889@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Max", "Ernst", "maxErnst_dada@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Jorge", "Isaac", "MariaIsNobel@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Richard", "Nixon", "RicharNixon911@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Albert", "Camus", "alberCamuMarte@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Ernest", "Hemingway", "Scope@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Henry", "Martineau", "HarryMartineau1943@gmail.com", "2023-04-23");

INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Juan", "Valdez", "juanxsvaldez2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Camilo", "Gutierrez", "camiloGZ2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Mr. Jhon", "Doe", "jhon_doe2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Linus", "Torvalds", "linustorvals2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Rasmus", "Lerdford", "rasmuss.lerdford2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Erich", "gamma", "Erich_gamma_2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Richard", "Helm", "Richard_Helm2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Salomon", "King", "salomonKing2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("David", "king", "davidKing2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Charles", "Chaplin", "CharlesChaplin1889_2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Max", "Ernst", "maxErnst_dada2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Jorge", "Isaac", "MariaIsNobel2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Richard", "Nixon", "RicharNixon911_2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Albert", "Camus", "alberCamuMarte2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Ernest", "Hemingway", "Scope2@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Henry", "Martineau", "HarryMartineau1943_2@gmail.com", "2023-04-23");


INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Juan", "Valdez", "juanxsvaldez3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Camilo", "Gutierrez", "camiloGZ3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Mr. Jhon", "Doe", "jhon_doe3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Linus", "Torvalds", "linustorvals3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Rasmus", "Lerdford", "rasmuss.lerdford3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Erich", "gamma", "Erich_gamma_3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Richard", "Helm", "Richard_Helm3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Salomon", "King", "salomonKing3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("David", "king", "davidKing3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Charles", "Chaplin", "CharlesChaplin1889_3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Max", "Ernst", "maxErnst_dada3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Jorge", "Isaac", "MariaIsNobel3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Richard", "Nixon", "RicharNixon911_3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Albert", "Camus", "alberCamuMarte3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Ernest", "Hemingway", "Scope3@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Henry", "Martineau", "HarryMartineau1943_3@gmail.com", "2023-04-23");

INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Juan", "Valdez", "juanxsvaldez4@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Camilo", "Gutierrez", "camiloGZ4@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Mr. Jhon", "Doe", "jhon_doe4@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Linus", "Torvalds", "linustorvals4@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Rasmus", "Lerdford", "rasmuss.lerdford4@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Erich", "gamma", "Erich_gamma_4@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Richard", "Helm", "Richard_Helm4@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Salomon", "King", "salomonKing4@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("David", "king", "davidKing4@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Charles", "Chaplin", "CharlesChaplin1889_4@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Max", "Ernst", "maxErnst_dada4@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Jorge", "Isaac", "MariaIsNobel4@gmail.com", "2023-04-23");
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES("Richard", "Nixon", "RicharNixon911_4@gmail.com", "2023-04-23");